import:
  resolutions: both
  chunk_size: 32
  use_sharding: false
  chunks_per_shard: 1
  batch_size: 32
  gpu_fp16: true
  use_kvikio_zarr: true
  full: true
  downsampled:
    size:
    - 640
    - 640
    method: bilinear
    formats: [gray]
    chunk_size: 128
    preserve_aspect: false
  post_compress:
    enable: false
    targets:
    - downsampled
    method: lz4
    level: 1
    delete_uncompressed: false
  include_system_info: true
background:
  sample_size: 500
  seed: 195
  method: mode
  compute_full: true
  compute_ds: true
detect:
  ds_thresh: 13
  se1_radius: 2
  se4_radius: 10
  min_area: 85
  max_area: 5000
  max_fish: 1
  dish_mask: &id001
    shape: circle
    center:
    - 328
    - 310
    radius: 295
    hough_params:
      param1: 50
      param2: 30
      radius_adjustment: 4
    source:
      array: images_ds
      frame: 22724
      timestamp: '2025-09-30T23:21:53.102671'
crop:
  dish_mask: *id001
  roi_sz:
  - 256
  - 256
  scheduler: distributed
  source_type: interpolated        # detect | filtered | interpolated
  source_path: null                # set to detect_runs/<run> or refined_detect_runs/<run>/interpolated to pin a run
  num_workers: 30
keypoints:
  method: traditional         # 'traditional' or 'yolo'
  scheduler: distributed  # or 'processes', 'threads'
  num_workers: 20
  threads_per_worker: 2
  memory_limit: '50GB'
  roi_thresh: 50
  se1_radius: 1
  se2_radius: 2
  min_area: 5
  adaptive_steps: 5
  thresh_decrement: 5
  min_valid_angle: 10.0
  min_triangle_area: 100.0
refine_detect:
  filters:
    remove_jumps: true
    remove_blips: false  # Usually keep blips, they're just after gaps
  
  max_gap: 50
  interpolation_method: linear
