train: ./                       # YOLO dummy values
val: ./
nc: 1
names: ['fish']
task: pose

kpt_shape: [3, 2]

datasets:
  arena4:
    zarr_path: /nvme1/sesh3/2025-09-23T22-11-11Z_arena_4_chaser_arena4.zarr
    source_type: filtered
    split:
      train: 0.8
      val: 0.2

training_params:
  model: yolov8n-pose.pt
  epochs: 1
  batch: 32
  imgsz: 256
  lr0: 0.001
  momentum: 0.9
  weight_decay: 0.0005
  patience: 10
  device: '0'
  project: runs/pose
