[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --color=yes
norecursedirs = scraps .git .tox dist build *.egg
filterwarnings =
    ignore:`product` is deprecated as of NumPy 1.25.0.*:DeprecationWarning:skimage\.measure\._regionprops
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    gpu: marks tests that require GPU
