"""Citrus pose observations v1 in the unified H5: optional, required once declared.

Fixtures are Citrus's frozen reference bytes (agent-contracts
citrus-pose-observation-v1, 49142e6), pinned by digest; they cannot be
regenerated byte for byte.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import shutil

import h5py
import pytest

from fisheye.shared.unified_h5 import UnifiedH5ContractError
from fisheye.shared.unified_h5 import pose
from fisheye.shared.unified_h5.integrity import validate_internal_integrity

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures" / "citrus_pose_observation_v1"
DIGESTS = {
    "pose_complete.h5": "4856d50e71c9197435f7470b3ef2d63bd69e84abffd6bd1529b08b77d2f67a25",
    "pose_failed.h5": "9183ffbe254b33c707d3659b769417d3cfc76299d2361af224b369398dd62e75",
    "pose_absent.h5": "8abb6b52fcec95c7b9db603e231c52125f7348c0eadbb2a986808bad1fd5caf0",
}


def test_vendored_fixtures_are_the_published_bytes():
    for name, digest in DIGESTS.items():
        assert hashlib.sha256((FIXTURES / name).read_bytes()).hexdigest() == digest


def test_a_complete_pose_is_admitted_with_its_rows():
    with h5py.File(FIXTURES / "pose_complete.h5", "r") as h5:
        assert validate_internal_integrity(h5).pose_rows == 4 + 3 + 9


def test_an_absent_pose_is_admitted_without_one():
    with h5py.File(FIXTURES / "pose_absent.h5", "r") as h5:
        assert validate_internal_integrity(h5).pose_rows is None


def test_a_declared_pose_that_failed_refuses_the_file():
    with h5py.File(FIXTURES / "pose_failed.h5", "r") as h5:
        with pytest.raises(UnifiedH5ContractError, match="unified_session_not_complete"):
            validate_internal_integrity(h5)


def _outcomes(h5) -> dict:
    data = json.loads(h5["/metadata/component_outcomes_json"][()])
    return {row["component_id"]: row for row in data["components"]}


def _copy(tmp_path: Path, name: str = "pose_complete.h5") -> Path:
    return Path(shutil.copy(FIXTURES / name, tmp_path / name))


def _check(path: Path, *, outcomes=None, receipts=frozenset({pose.COMPONENT})):
    with h5py.File(path, "r") as h5:
        return pose.validate_pose_observations(
            h5, _outcomes(h5) if outcomes is None else outcomes, set(receipts)
        )


def test_the_complete_fixture_passes_the_component_rules(tmp_path):
    assert _check(_copy(tmp_path)) == 16


@pytest.mark.parametrize(
    ("name", "outcomes", "receipts"),
    [
        ("pose_complete.h5", {}, {pose.COMPONENT}),  # group and receipt, no outcome row
        ("pose_complete.h5", None, set()),  # no manifest receipt
        ("pose_absent.h5", {pose.COMPONENT: {"requirement": "required"}}, set()),  # row only
    ],
)
def test_a_partial_declaration_is_refused(tmp_path, name, outcomes, receipts):
    with pytest.raises(UnifiedH5ContractError, match="pose_declaration_incomplete"):
        _check(_copy(tmp_path, name), outcomes=outcomes, receipts=receipts)


def test_an_outcome_that_disagrees_with_the_tables_is_refused(tmp_path):
    path = _copy(tmp_path)
    with h5py.File(path, "r") as h5:
        outcomes = _outcomes(h5)
    outcomes[pose.COMPONENT] = dict(outcomes[pose.COMPONENT], expected_rows=17, written_rows=17)
    with pytest.raises(UnifiedH5ContractError, match="pose_outcome_count_mismatch"):
        _check(path, outcomes=outcomes)


def _rewrite_receipt(path: Path, **changes) -> None:
    with h5py.File(path, "r+") as h5:
        receipt = json.loads(h5[pose.RECEIPT][()])
        receipt.update(changes)
        del h5[pose.RECEIPT]
        h5.create_dataset(
            pose.RECEIPT, data=json.dumps(receipt, sort_keys=True, separators=(",", ":")),
            dtype=h5py.string_dtype("utf-8"),
        )


def test_a_receipt_that_disagrees_with_a_table_is_refused(tmp_path):
    path = _copy(tmp_path)
    _rewrite_receipt(path, keypoints_expected=10, keypoints_written=10)
    with pytest.raises(UnifiedH5ContractError, match="pose_receipt_count_mismatch:keypoints"):
        _check(path)


def test_a_receipt_outside_the_closed_schema_is_refused(tmp_path):
    path = _copy(tmp_path)
    _rewrite_receipt(path, reason="")
    with pytest.raises(UnifiedH5ContractError, match="pose_receipt_schema"):
        _check(path)


def test_an_integer_schema_version_attribute_is_refused(tmp_path):
    path = _copy(tmp_path)
    with h5py.File(path, "r+") as h5:
        h5["/observations/pose/objects"].attrs["schema_version"] = 1
    with pytest.raises(UnifiedH5ContractError, match="pose_table_attributes_mismatch:objects"):
        _check(path)


def test_a_keypoint_owned_by_the_wrong_object_is_refused(tmp_path):
    path = _copy(tmp_path)
    with h5py.File(path, "r+") as h5:
        keypoints = h5["/observations/pose/keypoints"]
        row = keypoints[0]
        row["object_row"] = row["object_row"] + 1
        keypoints[0] = row
    with pytest.raises(UnifiedH5ContractError, match="pose_row_owner_mismatch"):
        _check(path)


def test_the_pinned_contract_detects_drift(monkeypatch):
    pose._pinned.cache_clear()
    pose._validator.cache_clear()
    monkeypatch.setitem(pose._PINNED, "tables", ("citrus_pose_observation_tables.v1.json", "0" * 64))
    try:
        with pytest.raises(UnifiedH5ContractError, match="packaged_contract_drift"):
            pose._pinned("tables")
    finally:
        pose._pinned.cache_clear()
        pose._validator.cache_clear()
