#!/usr/bin/env python3
"""Generate docs/registry_schema_reference.md from SQLite schema metadata."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from fisheye.registry.db import Registry
from fisheye.registry.migrations import MIGRATION_METHODS


def _quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _pragma_rows(conn: Any, pragma_name: str, object_name: str) -> list[Any]:
    sql = f"PRAGMA {pragma_name}({_quote_ident(object_name)});"
    return list(conn.execute(sql).fetchall())


def _yes_no(value: Any) -> str:
    return "yes" if bool(value) else "no"


def _render_column_table(columns: list[Any]) -> list[str]:
    lines = [
        "| Column | Type | Nullable | PK | Default |",
        "|---|---|---|---|---|",
    ]
    for col in columns:
        name = str(col["name"])
        col_type = str(col["type"] or "")
        not_null = bool(col["notnull"])
        pk = bool(col["pk"])
        nullable = "no" if (not_null or pk) else "yes"
        default = str(col["dflt_value"]) if col["dflt_value"] is not None else ""
        lines.append(f"| `{name}` | `{col_type}` | {nullable} | {_yes_no(pk)} | `{default}` |")
    return lines


def _render_view_column_table(columns: list[Any]) -> list[str]:
    """Render only the schema information SQLite actually declares for views.

    ``PRAGMA table_info`` synthesizes type affinities for view expressions, and
    those inferred values change between SQLite releases.  A view declaration
    guarantees its column names and SQL definition, not those inferred types.
    """
    lines = [
        "| Column | Type | Nullable | PK | Default |",
        "|---|---|---|---|---|",
    ]
    for col in columns:
        name = str(col["name"])
        not_null = bool(col["notnull"])
        pk = bool(col["pk"])
        nullable = "no" if (not_null or pk) else "yes"
        default = str(col["dflt_value"]) if col["dflt_value"] is not None else ""
        lines.append(f"| `{name}` | `` | {nullable} | {_yes_no(pk)} | `{default}` |")
    return lines


def _generate_markdown(registry: Registry) -> str:
    conn = registry.conn
    objects = list(
        conn.execute(
            """
            SELECT name, type, sql
            FROM sqlite_master
            WHERE type IN ('table', 'view')
              AND name NOT LIKE 'sqlite_%'
            ORDER BY type, name;
            """
        ).fetchall()
    )

    tables = [row for row in objects if str(row["type"]) == "table"]
    views = [row for row in objects if str(row["type"]) == "view"]
    table_sql_by_name = {str(row["name"]): (str(row["sql"]) if row["sql"] else "") for row in tables}

    total_columns = 0
    table_columns: dict[str, list[Any]] = {}
    view_columns: dict[str, list[Any]] = {}
    for row in tables:
        name = str(row["name"])
        cols = _pragma_rows(conn, "table_info", name)
        table_columns[name] = cols
        total_columns += len(cols)
    for row in views:
        name = str(row["name"])
        cols = _pragma_rows(conn, "table_info", name)
        view_columns[name] = cols
        total_columns += len(cols)

    schema_version = int(MIGRATION_METHODS[-1][0])

    lines: list[str] = []
    lines.append("# Registry Schema Reference")
    lines.append("")
    lines.append("> Auto-generated by `scripts/generate_registry_schema_reference.py`. Do not edit by hand.")
    lines.append(f"> Registry schema migration: `{schema_version}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Tables: `{len(tables)}`")
    lines.append(f"- Views: `{len(views)}`")
    lines.append(f"- Total columns: `{total_columns}`")

    lines.append("")
    lines.append("## Tables")
    lines.append("")

    for table_row in tables:
        table_name = str(table_row["name"])
        lines.append(f"### `{table_name}`")
        lines.append("")
        columns = table_columns[table_name]
        lines.extend(_render_column_table(columns))
        lines.append("")
        lines.append("#### Definition")
        lines.append("")
        lines.append("```sql")
        table_definition = table_sql_by_name.get(table_name, "")
        lines.append(table_definition if table_definition else "-- definition unavailable")
        lines.append("```")
        lines.append("")

        fk_rows = _pragma_rows(conn, "foreign_key_list", table_name)
        if fk_rows:
            lines.append("#### Foreign Keys")
            lines.append("")
            lines.append("| FK ID | From | To | On Update | On Delete | Match |")
            lines.append("|---|---|---|---|---|---|")
            for fk in fk_rows:
                fk_id = str(fk["id"])
                from_col = str(fk["from"])
                to_table = str(fk["table"])
                to_col = str(fk["to"])
                on_update = str(fk["on_update"])
                on_delete = str(fk["on_delete"])
                match = str(fk["match"])
                lines.append(
                    f"| `{fk_id}` | `{from_col}` | `{to_table}.{to_col}` | `{on_update}` | `{on_delete}` | `{match}` |"
                )
            lines.append("")

        index_rows = _pragma_rows(conn, "index_list", table_name)
        if index_rows:
            lines.append("#### Indexes")
            lines.append("")
            lines.append("| Index | Unique | Origin | Partial | Columns |")
            lines.append("|---|---|---|---|---|")
            for idx in index_rows:
                index_name = str(idx["name"])
                cols = _pragma_rows(conn, "index_info", index_name)
                col_names = ", ".join(f"`{str(col['name'])}`" for col in cols if col["name"] is not None)
                lines.append(
                    "| "
                    + f"`{index_name}` | {_yes_no(idx['unique'])} | `{str(idx['origin'])}` | {_yes_no(idx['partial'])} | {col_names} |"
                )
            lines.append("")

    lines.append("## Views")
    lines.append("")

    sql_by_name = {str(row["name"]): (str(row["sql"]) if row["sql"] else "") for row in views}

    for view_row in views:
        view_name = str(view_row["name"])
        lines.append(f"### `{view_name}`")
        lines.append("")
        lines.append("#### Columns")
        lines.append("")
        lines.append(
            "SQLite-inferred view affinities are intentionally omitted because they "
            "vary across SQLite releases."
        )
        lines.append("")
        lines.extend(_render_view_column_table(view_columns[view_name]))
        lines.append("")
        lines.append("#### Definition")
        lines.append("")
        lines.append("```sql")
        definition = sql_by_name.get(view_name, "")
        lines.append(definition if definition else "-- definition unavailable")
        lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _open_registry(db_arg: str | None) -> Registry:
    if db_arg is None:
        return Registry(Path(":memory:"))

    if db_arg == ":memory:":
        return Registry(Path(":memory:"))

    db_path = Path(db_arg).expanduser()
    if not db_path.exists():
        raise FileNotFoundError(f"Registry database not found: {db_path}")
    return Registry(db_path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate registry schema markdown reference.")
    parser.add_argument("--db", type=str, default=None, help="Optional path to an existing registry SQLite database.")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/registry_schema_reference.md"),
        help="Output markdown path.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the output is missing or differs; do not write it.",
    )
    args = parser.parse_args(argv)

    registry = _open_registry(args.db)
    try:
        content = _generate_markdown(registry)
    finally:
        registry.close()

    output_path = args.output
    if args.check:
        if not output_path.is_file():
            print(f"Schema reference is missing: {output_path}")
            return 1
        if output_path.read_text(encoding="utf-8") != content:
            print(
                "Registry schema reference is stale; regenerate with "
                f"scripts/py scripts/generate_registry_schema_reference.py --output {output_path}"
            )
            return 1
        print(f"Registry schema reference is current: {output_path}")
        return 0
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote schema reference: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
