# ================================================================================
# ZARR YOLO TRAINING CONFIGURATION
# ================================================================================
# This file serves as the complete recipe for a training run.
# It defines the data, hyperparameters, and will be updated with
# the results and metadata after the training is complete.
# ================================================================================

# Part 1: DATA CONFIGURATION
# Define the datasets and how they are sampled
# --------------------------------------------------------------------------------
data_config:
  zarr_paths:
  - /home/delahantyj@hhmi.org/Desktop/concentricOMR3/video.zarr
  - /home/delahantyj@hhmi.org/Desktop/concentricOMR3/longer_edge.zarr
  task: detect
  split_ratio: 0.8
  random_seed: 42
  sampling_strategy: balanced # Options: balanced, proportional, weighted

# Part 2: MODEL & TRAINING HYPERPARAMETERS
# Define the model and how it should be trained.
# --------------------------------------------------------------------------------
training_config:
  # Model setup
  model_name: yolov8n.pt
  nc: 1
  names: ['fish']

  # Core hyperparameters
  epochs: 50
  batch_size: 16
  imgsz: 640
  optimizer: AdamW
  lr0: 0.002
  momentum: 0.9
  weight_decay: 0.0005

  # Other training settings
  patience: 50
  device: '0'

# ================================================================================
# Part 3: TRAINING HISTORY & METADATA
# This section is automatically populated by the training script after a run.
# It ensures that this file becomes a complete, reproducible record.
# --------------------------------------------------------------------------------
training_history:
  # --- Run Details ---
  training_run_name: "multi_zarr_train_example"
  output_directory: "runs/detect/multi_zarr_train_example"
  final_model_path: "runs/detect/multi_zarr_train_example/weights/best.pt"
  training_start_time: "2025-07-28 17:00:00"
  training_duration_hours: 0.5

  # --- Code & Environment ---
  git_commit_hash: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
  python_version: "3.10.18"
  torch_version: "2.5.1+cu121"
  ultralytics_version: "8.3.169"

  # --- Final Validation Metrics ---
  final_metrics:
    box_loss: 2.416
    cls_loss: 14.39
    dfl_loss: 0.8117
    # mAP50-95, precision, recall would also be logged here