# src/pipeline_config.yaml
#
# Centralized configuration for the Zarr data processing pipeline.
# This file defines all parameters for each stage of the tracking workflow.

import:
  downsample_size: [640, 640]
  chunk_size: 32
  batch_size: 32

background:
  sample_size: 100
  seed: 42

crop:
  roi_sz: [256, 256]
  ds_thresh: 27
  se1_radius: 1
  se4_radius: 6
  dish_mask:
    shape: 'circle'
    hough_param1: 88 # Higher threshold to internal Canny edge detector through gradient detection
    hough_param2: 188 # Accumulator threshold for circle detection; basically how "confident" you can be that the object detected is a circle
    radius_adj: 4 # Radius adjustment for detected circles; positive values increase radius, negative decrease

refine:
  # Max distance (as fraction of image width) detections can move to be considered valid
  max_jump_norm: 0.1


track:
  roi_sz: [256, 256]
  roi_thresh: 115
  se1_radius: 1
  se2_radius: 2