import:
  downsample_size:
  - 640
  - 640
  chunk_size: 32
  batch_size: 32
background:
  sample_size: -1
  seed: 42
detect:
  ds_thresh: 25
  se1_radius: 1
  se4_radius: 8
  dish_mask:
    shape: rectangle
    roi:
    - 55
    - 60
    - 530
    - 407
  min_area: 50
  max_area: 500
  max_fish: 12
crop:
  roi_sz:
  - 256
  - 256
  ds_thresh: 25
  se1_radius: 1
  se4_radius: 8
  min_fish_area: 50
  max_fish_area: 500
refine:
  max_jump_norm: 0.1
track:
  roi_sz:
  - 256
  - 256
  roi_thresh: 115
  se1_radius: 1
  se2_radius: 2
assign_ids:
  sub_dish_rois:
  - id: 0
    roi_pixels:
    - 61
    - 76
    - 73
    - 181
  - id: 1
    roi_pixels:
    - 144
    - 75
    - 69
    - 177
  - id: 2
    roi_pixels:
    - 246
    - 76
    - 69
    - 180
  - id: 3
    roi_pixels:
    - 325
    - 77
    - 69
    - 178
  - id: 4
    roi_pixels:
    - 430
    - 76
    - 71
    - 177
  - id: 5
    roi_pixels:
    - 511
    - 75
    - 68
    - 180
  - id: 6
    roi_pixels:
    - 64
    - 275
    - 67
    - 179
  - id: 7
    roi_pixels:
    - 143
    - 278
    - 68
    - 178
  - id: 8
    roi_pixels:
    - 243
    - 277
    - 69
    - 180
  - id: 9
    roi_pixels:
    - 323
    - 277
    - 69
    - 178
  - id: 10
    roi_pixels:
    - 429
    - 278
    - 70
    - 180
  - id: 11
    roi_pixels:
    - 508
    - 276
    - 70
    - 182
