import:
  downsample_size:
  - 640
  - 640
  chunk_size: 32
  batch_size: 32
background:
  sample_size: 100
  seed: 42
detect:
  ds_thresh: 22
  se1_radius: 1
  se4_radius: 9
  dish_mask:
    shape: rectangle
    roi:
    - 55
    - 60
    - 530
    - 407
  min_area: 85
  max_area: 500
  max_fish: 12
crop:
  roi_sz:
  - 256
  - 256
  ds_thresh: 25
  se1_radius: 1
  se4_radius: 8
  min_fish_area: 50
  max_fish_area: 500
  dish_mask:
    shape: rectangle
    roi:
    - 59
    - 68
    - 520
    - 392
refine:
  max_jump_norm: 0.1
track:
  roi_sz:
  - 256
  - 256
  roi_thresh: 115
  se1_radius: 1
  se2_radius: 2
assign_ids:
  sub_dish_rois:
  - id: 0
    roi_pixels:
    - 59
    - 73
    - 71
    - 180
  - id: 1
    roi_pixels:
    - 139
    - 74
    - 71
    - 178
  - id: 2
    roi_pixels:
    - 241
    - 76
    - 70
    - 180
  - id: 3
    roi_pixels:
    - 320
    - 73
    - 70
    - 183
  - id: 4
    roi_pixels:
    - 425
    - 76
    - 71
    - 183
  - id: 5
    roi_pixels:
    - 503
    - 70
    - 73
    - 188
  - id: 6
    roi_pixels:
    - 53
    - 272
    - 75
    - 183
  - id: 7
    roi_pixels:
    - 137
    - 275
    - 71
    - 181
  - id: 8
    roi_pixels:
    - 236
    - 271
    - 72
    - 185
  - id: 9
    roi_pixels:
    - 317
    - 272
    - 70
    - 185
  - id: 10
    roi_pixels:
    - 421
    - 273
    - 73
    - 185
  - id: 11
    roi_pixels:
    - 502
    - 275
    - 70
    - 184
