#!/usr/bin/env python
#
# zarr_inspector.py
# Enhanced script to inspect the complete structure and metadata of Zarr archives
# generated by the fish tracking and analysis pipeline.
#
# Usage: python zarr_inspector.py /path/to/your/data.zarr

import zarr
import argparse
import json
import os
import numpy as np
from datetime import datetime
from rich.console import Console
from rich.table import Table
from rich.tree import Tree
from rich import box
from rich.panel import Panel
from rich.syntax import Syntax

# --- Helper Functions ---
def format_bytes(size: int) -> str:
    """Converts bytes to a human-readable format (KB, MB, GB)."""
    if size is None or size == 0:
        return "0 B"
    power = 1024
    n = 0
    power_labels = {0: '', 1: 'K', 2: 'M', 3: 'G', 4: 'T'}
    while size >= power and n < len(power_labels) - 1:
        size /= power
        n += 1
    return f"{size:.2f} {power_labels[n]}B"

def format_timestamp(timestamp_str: str) -> str:
    """Format ISO timestamp to readable format."""
    try:
        dt = datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
        return dt.strftime("%Y-%m-%d %H:%M:%S")
    except:
        return timestamp_str

def detect_pipeline_components(root):
    """Detect which pipeline components are present."""
    components = {
        'detection': False,
        'preprocessing': False,
        'calibration': False,
        'behavior_metrics': False,
        'bout_analysis': False,
        'bout_phase_analysis': False,
        'tracking': False,
        'multi_scale': False
    }
    
    # Check for detection data
    if 'detect_runs' in root or 'bboxes' in root:
        components['detection'] = True
    
    # Check for preprocessing (refinement, cropping, filtering)
    detection_groups = [REFINED_DETECT_GROUP, LEGACY_REFINED_DETECT_GROUP, 'filtered_runs', 'preprocessing', 'crop_runs']
    if any(group in root for group in detection_groups):
        components['preprocessing'] = True
    
    # Check for calibration
    if 'calibration' in root:
        components['calibration'] = True
    
    # Check for behavior metrics
    if 'behavior_metrics' in root:
        components['behavior_metrics'] = True
    
    # Check for bout analyses
    if 'bout_analysis' in root:
        components['bout_analysis'] = True
    
    if 'bout_phase_analysis' in root:
        components['bout_phase_analysis'] = True
    
    # Check for tracking data
    if 'tracking_runs' in root:
        components['tracking'] = True
        # Check if multi-scale
        if 'latest' in root['tracking_runs'].attrs:
            latest_run = root['tracking_runs'].attrs['latest']
            if f'tracking_runs/{latest_run}/tracking_results' in root:
                tracking_results = root[f'tracking_runs/{latest_run}/tracking_results']
                if 'column_names' in tracking_results.attrs:
                    column_names = tracking_results.attrs['column_names']
                    if len(column_names) >= 20 and 'bbox_x_norm_ds' in column_names:
                        components['multi_scale'] = True
    
    return components


def get_frame_counts_from_group(group, expected_length: int | None = None):
    """Return per-frame detection counts from a group if available."""
    if 'frame_counts' in group:
        counts = group['frame_counts'][:]
    elif 'frame_indices' in group:
        indices = group['frame_indices'][:]
        minlength = expected_length or (int(indices.max()) + 1 if indices.size else 0)
        counts = np.bincount(indices.astype(np.int64, copy=False), minlength=minlength)
    else:
        return None

    if expected_length is not None and len(counts) < expected_length:
        counts = np.pad(counts, (0, expected_length - len(counts)), mode='constant')
    return counts

def analyze_calibration(root, console):
    """Analyze and display calibration information."""
    if 'calibration' not in root:
        return
    
    calib = root['calibration']
    calib_table = Table(title="Calibration Data", box=box.ROUNDED)
    calib_table.add_column("Parameter", style="cyan")
    calib_table.add_column("Value", style="yellow")
    calib_table.add_column("Units", style="green")
    
    if 'pixel_to_mm' in calib.attrs:
        pixel_to_mm = calib.attrs['pixel_to_mm']
        calib_table.add_row("Pixel to mm", f"{pixel_to_mm:.6f}", "mm/pixel")
        calib_table.add_row("mm to pixel", f"{1/pixel_to_mm:.2f}", "pixels/mm")
    
    if 'fish_length_mm' in calib.attrs:
        calib_table.add_row("Fish length", f"{calib.attrs['fish_length_mm']:.1f}", "mm")
    
    if 'arena_diameter_mm' in calib.attrs:
        calib_table.add_row("Arena diameter", f"{calib.attrs['arena_diameter_mm']:.1f}", "mm")
    
    if 'measured_fps' in calib.attrs:
        calib_table.add_row("Measured FPS", f"{calib.attrs['measured_fps']:.2f}", "Hz")
    
    if 'created_at' in calib.attrs:
        calib_table.add_row("Calibrated", format_timestamp(calib.attrs['created_at']), "")
    
    console.print(calib_table)

def analyze_bout_phases(root, console):
    """Analyze bout phase analysis results."""
    if 'bout_phase_analysis' not in root:
        return
    
    analysis_group = root['bout_phase_analysis']
    
    # Get latest run
    if 'latest' not in analysis_group.attrs:
        return
    
    latest = analysis_group.attrs['latest']
    run_group = analysis_group[latest]
    
    # Display phase comparison
    if 'summary_statistics' in run_group.attrs:
        stats = run_group.attrs['summary_statistics']
        
        phase_table = Table(title="Training Phase Bout Analysis", box=box.ROUNDED)
        phase_table.add_column("Phase", style="cyan")
        phase_table.add_column("Bouts", style="yellow", justify="right")
        phase_table.add_column("Rate (bouts/min)", style="green", justify="right")
        phase_table.add_column("Active %", style="magenta", justify="right")
        phase_table.add_column("Change from Pre", style="red", justify="right")
        
        if 'phase_comparison' in stats:
            for phase_name, phase_data in stats['phase_comparison'].items():
                phase_label = phase_name.replace('_', ' ').title()
                n_bouts = phase_data.get('n_bouts', 0)
                bout_rate = phase_data.get('bout_rate_per_min', 0)
                percent_active = phase_data.get('percent_active', 0)
                
                # Get change from pre-training
                change_str = "-"
                if 'bout_rate_change_from_pre' in phase_data:
                    change = phase_data['bout_rate_change_from_pre']
                    change_str = f"{change:+.1f}%"
                
                phase_table.add_row(
                    phase_label,
                    str(n_bouts),
                    f"{bout_rate:.1f}",
                    f"{percent_active:.1f}%",
                    change_str
                )
        
        console.print(phase_table)

def analyze_behavior_metrics(root, console):
    """Analyze behavior metrics if present."""
    if 'behavior_metrics' not in root:
        return
    
    metrics = root['behavior_metrics']
    
    metrics_table = Table(title="Behavior Metrics", box=box.ROUNDED)
    metrics_table.add_column("Metric", style="cyan")
    metrics_table.add_column("Value", style="yellow")
    metrics_table.add_column("Units", style="green")
    
    # Check for distance metrics
    if 'distance' in metrics:
        dist_group = metrics['distance']
        if 'total_distance' in dist_group.attrs:
            total_dist = dist_group.attrs['total_distance']
            metrics_table.add_row("Total distance", f"{total_dist:.1f}", "pixels")
            
            # If calibration exists, show mm too
            if 'calibration' in root and 'pixel_to_mm' in root['calibration'].attrs:
                pixel_to_mm = root['calibration'].attrs['pixel_to_mm']
                total_mm = total_dist * pixel_to_mm
                metrics_table.add_row("Total distance", f"{total_mm:.1f}", "mm")
    
    # Check for speed metrics
    if 'speed' in metrics:
        speed_group = metrics['speed']
        if 'mean_speed' in speed_group.attrs:
            mean_speed = speed_group.attrs['mean_speed']
            metrics_table.add_row("Mean speed", f"{mean_speed:.1f}", "px/s")
            
            if 'calibration' in root and 'pixel_to_mm' in root['calibration'].attrs:
                pixel_to_mm = root['calibration'].attrs['pixel_to_mm']
                mean_speed_mm = mean_speed * pixel_to_mm
                metrics_table.add_row("Mean speed", f"{mean_speed_mm:.2f}", "mm/s")
        
        if 'max_speed' in speed_group.attrs:
            max_speed = speed_group.attrs['max_speed']
            metrics_table.add_row("Max speed", f"{max_speed:.1f}", "px/s")
    
    console.print(metrics_table)

def analyze_preprocessing_pipeline(root, console):
    """Analyze the preprocessing pipeline stages."""
    stages = []
    
    detect_counts = None
    if 'detect_runs' in root and root['detect_runs'].attrs.get('latest'):
        latest_detect = root['detect_runs'].attrs['latest']
        detect_group = root[f'detect_runs/{latest_detect}']
        detect_counts = get_frame_counts_from_group(detect_group)
        if detect_counts is not None and len(detect_counts) > 0:
            coverage = (detect_counts > 0).sum() / len(detect_counts) * 100
            stages.append(('Detected', coverage, len(detect_counts)))
    
    refined_root = None
    if REFINED_DETECT_GROUP in root and root[REFINED_DETECT_GROUP].attrs.get('latest'):
        refined_root = root[REFINED_DETECT_GROUP]
    elif LEGACY_REFINED_DETECT_GROUP in root and root[LEGACY_REFINED_DETECT_GROUP].attrs.get('latest'):
        refined_root = root[LEGACY_REFINED_DETECT_GROUP]
    if refined_root is not None:
        latest_refined = refined_root.attrs['latest']
        refined_group = refined_root[latest_refined]
        expected_length = len(detect_counts) if detect_counts is not None else None
        if 'filtered' in refined_group:
            filtered_counts = get_frame_counts_from_group(refined_group['filtered'], expected_length)
            if filtered_counts is not None and len(filtered_counts) > 0:
                coverage = (filtered_counts > 0).sum() / len(filtered_counts) * 100
                stages.append(('Filtered', coverage, len(filtered_counts)))
        if 'interpolated' in refined_group:
            interpolated_counts = get_frame_counts_from_group(refined_group['interpolated'], expected_length)
            if interpolated_counts is not None and len(interpolated_counts) > 0:
                coverage = (interpolated_counts > 0).sum() / len(interpolated_counts) * 100
                stages.append(('Interpolated', coverage, len(interpolated_counts)))
    
    if stages:
        pipeline_table = Table(title="🔧 Preprocessing Pipeline", box=box.ROUNDED)
        pipeline_table.add_column("Stage", style="cyan")
        pipeline_table.add_column("Coverage", style="yellow", justify="right")
        pipeline_table.add_column("Frames", style="green", justify="right")
        pipeline_table.add_column("Change", style="magenta", justify="right")
        
        prev_coverage = None
        for stage_name, coverage, frames in stages:
            change_str = "-"
            if prev_coverage is not None:
                change = coverage - prev_coverage
                change_str = f"{change:+.1f}%"
            
            pipeline_table.add_row(
                stage_name,
                f"{coverage:.1f}%",
                str(frames),
                change_str
            )
            prev_coverage = coverage
        
        console.print(pipeline_table)

def build_enhanced_tree(group: zarr.Group, tree_branch: Tree, max_depth: int = 3, current_depth: int = 0):
    """Builds an enhanced tree view with better formatting and depth control."""
    if current_depth >= max_depth:
        tree_branch.add("[dim]... (more groups/arrays)[/dim]")
        return
    
    group_items = sorted(list(group.groups()))
    dataset_items = sorted(list(group.arrays()))
    
    # Add groups with icons
    for name, grp_obj in group_items:
        # Choose icon based on group name
        if 'calibration' in name:
            icon = "📐"
        elif 'bout' in name:
            icon = "🏊"
        elif 'behavior' in name or 'metrics' in name:
            icon = "📊"
        elif 'preprocessing' in name or 'filtered' in name:
            icon = "🔧"
        elif 'runs' in name:
            icon = "🔄"
        else:
            icon = "📁"
        
        # Check if it has a 'latest' attribute
        latest_info = ""
        if 'latest' in grp_obj.attrs:
            latest = grp_obj.attrs['latest'].split('/')[-1]
            latest_info = f" [dim]→ {latest}[/dim]"
        
        branch = tree_branch.add(f"{icon} [bold blue]{name}/[/bold blue]{latest_info}")
        build_enhanced_tree(grp_obj, branch, max_depth, current_depth + 1)
    
    # Add arrays with better formatting
    for name, arr_obj in dataset_items:
        # Format array info
        shape_str = "×".join(map(str, arr_obj.shape))
        size_str = format_bytes(arr_obj.nbytes)
        
        # Choose icon based on array name
        if 'bbox' in name:
            icon = "📦"
        elif 'speed' in name or 'distance' in name:
            icon = "📈"
        elif 'mask' in name:
            icon = "🎭"
        else:
            icon = "📊"
        
        tree_branch.add(f"{icon} [green]{name}[/green] [dim]({shape_str}, {arr_obj.dtype}, {size_str})[/dim]")

def print_summary_panel(console: Console, root, components, zarr_path: str):
    """Print a summary panel of the zarr contents."""
    summary_lines = []
    
    # Basic info
    if 'fps' in root.attrs:
        summary_lines.append(f"Frame rate: {root.attrs['fps']} fps")
    
    if 'frame_count' in root.attrs:
        duration = root.attrs['frame_count'] / root.attrs.get('fps', 60) / 60
        summary_lines.append(f"Duration: {duration:.1f} minutes ({root.attrs['frame_count']} frames)")
    
    # Component status with emojis
    summary_lines.append("\nComponents:")
    status = "✅" if components['detection'] else "❌"
    summary_lines.append(f"  {status} Detection data")
    
    status = "✅" if components['preprocessing'] else "❌"
    summary_lines.append(f"  {status} Preprocessing (filtering/interpolation)")
    
    status = "✅" if components['calibration'] else "❌"
    summary_lines.append(f"  {status} Calibration (real-world units)")
    
    status = "✅" if components['behavior_metrics'] else "❌"
    summary_lines.append(f"  {status} Behavior metrics")
    
    status = "✅" if components['bout_analysis'] else "❌"
    summary_lines.append(f"  {status} Bout analysis")
    
    status = "✅" if components['bout_phase_analysis'] else "❌"
    summary_lines.append(f"  {status} Training phase analysis")
    
    # Detection coverage from latest run
    if 'detect_runs' in root and root['detect_runs'].attrs.get('latest'):
        latest_detect = root['detect_runs'].attrs['latest']
        detect_group = root[f'detect_runs/{latest_detect}']
        if 'frame_counts' in detect_group:
            counts = detect_group['frame_counts'][:]
            if len(counts) > 0:
                coverage = (counts > 0).sum() / len(counts) * 100
                summary_lines.append(f"\nDetection coverage: {coverage:.1f}% across {len(counts)} frames")
                total_dets = int(counts.sum())
                summary_lines.append(f"Total detections: {total_dets:,}")
    
    # File size
    total_size = 0
    store_path = None
    store = root.store
    for attr in ('path', 'directory', '_path'):
        if hasattr(store, attr):
            candidate = getattr(store, attr)
            if isinstance(candidate, str):
                store_path = candidate
                break
    if store_path is None:
        store_path = os.path.abspath(zarr_path)
    if os.path.isdir(store_path):
        for path, _, files in os.walk(store_path):
            for f in files:
                fp = os.path.join(path, f)
                if os.path.exists(fp):
                    total_size += os.path.getsize(fp)
    summary_lines.append(f"Total size: {format_bytes(total_size)}")
    
    panel = Panel(
        "\n".join(summary_lines),
        title="📊 Zarr Archive Summary",
        border_style="cyan",
        padding=(1, 2)
    )
    console.print(panel)


def print_environment_info(console: Console, root) -> None:
    """Print environment/provenance info for the most recent runs."""
    env_rows = []

    def add_entry(stage_label: str, run_name: str, group):
        if group is None:
            return
        prov = group.attrs.get('provenance', {})
        code = group.attrs.get('code_version', {})
        git_info = prov.get('git') if isinstance(prov.get('git'), dict) else {}

        git_commit = code.get('git_commit') or git_info.get('commit_hash') or git_info.get('git_commit')
        host = code.get('hostname') or prov.get('hostname') or git_info.get('hostname')
        created = (prov.get('created_at_utc') or
                   group.attrs.get('detect_timestamp_utc') or
                   group.attrs.get('crop_timestamp_utc') or
                   group.attrs.get('refinement_timestamp') or
                   group.attrs.get('assign_ids_timestamp_utc') or
                   group.attrs.get('analysis_timestamp'))

        command = prov.get('command') or prov.get('cmd')
        if command and len(command) > 80:
            command = command[:77] + "..."

        env_rows.append((stage_label, run_name, created or '—', host or '—', git_commit or '—', command or '—'))

    def latest_group(*paths: str):
        for path in paths:
            if path not in root:
                continue
            group = root[path]
            latest = group.attrs.get('latest')
            if not latest or latest not in group:
                continue
            return latest, group[latest]
        return None, None

    # Detect run
    run_name, run_group = latest_group('detect_runs')
    if run_group is not None:
        add_entry('Detect', run_name, run_group)

        # Quality run inside detect
        quality_group = run_group.get('quality_reports') if 'quality_reports' in run_group else None
        if quality_group is not None:
            latest_quality = quality_group.attrs.get('latest')
            if latest_quality and latest_quality in quality_group:
                add_entry('Quality', latest_quality, quality_group[latest_quality])

    # Refined run
    run_name, run_group = latest_group(REFINED_DETECT_GROUP, LEGACY_REFINED_DETECT_GROUP)
    if run_group is not None:
        add_entry('Refine', run_name, run_group)

    # Crop run
    run_name, run_group = latest_group('crop_runs')
    if run_group is not None:
        add_entry('Crop', run_name, run_group)

    # ID assignment run
    run_name, run_group = latest_group('id_assignment_runs')
    if run_group is not None:
        add_entry('Assign IDs', run_name, run_group)

    if env_rows:
        env_table = Table(title="⚙️ Run Environment", box=box.ROUNDED)
        env_table.add_column("Stage", style="cyan")
        env_table.add_column("Run", style="yellow")
        env_table.add_column("Created", style="green")
        env_table.add_column("Host", style="magenta")
        env_table.add_column("Git Commit", style="dim")
        env_table.add_column("Command", style="white")

        for row in env_rows:
            env_table.add_row(*row)

        console.print()
        console.print(env_table)

def inspect_zarr_archive(zarr_path: str, tree_depth: int = 3):
    """Main function to inspect a Zarr archive."""
    console = Console()
    
    # Header
    console.rule(f"[bold cyan]Zarr Archive Inspector[/bold cyan]", style="cyan")
    console.print(f"[dim]Path: {os.path.abspath(zarr_path)}[/dim]\n")
    
    try:
        root = zarr.open(zarr_path, mode='r')
    except Exception as e:
        console.print(f"[bold red]Error:[/bold red] Could not open Zarr archive: {e}")
        return
    
    # Detect components
    components = detect_pipeline_components(root)
    
    # Summary panel and environment info
    print_summary_panel(console, root, components, zarr_path)
    print_environment_info(console, root)
    
    # Archive structure tree
    console.print("\n[bold]📁 Archive Structure[/bold]")
    tree = Tree(f"[bold cyan]{os.path.basename(zarr_path)}[/bold cyan]")
    build_enhanced_tree(root, tree, max_depth=tree_depth)
    console.print(tree)
    
    # Component-specific analyses
    if components['calibration']:
        console.print()
        analyze_calibration(root, console)
    
    if components['preprocessing']:
        console.print()
        analyze_preprocessing_pipeline(root, console)
    
    if components['behavior_metrics']:
        console.print()
        analyze_behavior_metrics(root, console)
    
    if components['bout_phase_analysis']:
        console.print()
        analyze_bout_phases(root, console)
    
    # Metadata details for specific groups
    console.print("\n[bold] Metadata Details[/bold]")
    
    # Show latest runs for each analysis type
    analysis_groups = [
        ([REFINED_DETECT_GROUP, LEGACY_REFINED_DETECT_GROUP], 'Refinement'),
        (['filtered_runs'], 'Filtering'),
        (['preprocessing'], 'Interpolation'),
        (['bout_analysis'], 'Bout Analysis'),
        (['bout_phase_analysis'], 'Phase Analysis')
    ]
    
    for group_names, display_name in analysis_groups:
        group = None
        active_name = None
        for group_name in group_names:
            if group_name in root:
                group = root[group_name]
                active_name = group_name
                break
        if group is not None:
            if 'latest' in group.attrs:
                latest = group.attrs['latest']
                console.print(f"\n[cyan]{display_name}:[/cyan]")
                console.print(f"  Latest run: [yellow]{latest}[/yellow]")
                
                # Get run details
                try:
                    if 'runs/' in latest:
                        run_group = group[latest.replace('runs/', 'runs/')]
                    else:
                        run_group = group[latest]
                    
                    if 'created_at' in run_group.attrs:
                        console.print(f"  Created: [green]{format_timestamp(run_group.attrs['created_at'])}[/green]")
                    
                    if 'parameters' in run_group.attrs:
                        params = run_group.attrs['parameters']
                        console.print(f"  Parameters: [dim]{json.dumps(params, indent=4)}[/dim]")
                except:
                    pass
    
    # Footer with tips
    console.print("\n" + "─" * 80)
    console.print("[dim] Tips:[/dim]")
    console.print("[dim]  • Use --depth to control tree depth[/dim]")
    console.print("[dim]  • Groups with '→' have a 'latest' run[/dim]")
    console.print("[dim]  • ✅ = component present, ❌ = component missing[/dim]")

def main():
    parser = argparse.ArgumentParser(
        description="Enhanced inspector for fish tracking Zarr archives.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("zarr_path", type=str, 
                       help="Path to the Zarr archive directory to inspect.")
    parser.add_argument("--depth", type=int, default=3,
                       help="Maximum depth for tree display (default: 3)")
    
    args = parser.parse_args()
    inspect_zarr_archive(args.zarr_path, tree_depth=args.depth)

if __name__ == "__main__":
    main()
