#!/usr/bin/env python
#
# zarr_inspector.py
# Enhanced script to inspect the complete structure and metadata of Zarr archives
# generated by the fish tracking and analysis pipeline.
#
# Usage: python zarr_inspector.py /path/to/your/data.zarr

import zarr
import argparse
import json
import os
import numpy as np
from datetime import datetime
from rich.console import Console
from rich.table import Table
from rich.tree import Tree
from rich import box
from rich.panel import Panel
from rich.syntax import Syntax

# --- Helper Functions ---
def format_bytes(size: int) -> str:
    """Converts bytes to a human-readable format (KB, MB, GB)."""
    if size is None or size == 0:
        return "0 B"
    power = 1024
    n = 0
    power_labels = {0: '', 1: 'K', 2: 'M', 3: 'G', 4: 'T'}
    while size >= power and n < len(power_labels) - 1:
        size /= power
        n += 1
    return f"{size:.2f} {power_labels[n]}B"

def format_timestamp(timestamp_str: str) -> str:
    """Format ISO timestamp to readable format."""
    try:
        dt = datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
        return dt.strftime("%Y-%m-%d %H:%M:%S")
    except:
        return timestamp_str

def detect_pipeline_components(root):
    """Detect which pipeline components are present."""
    components = {
        'detection': False,
        'preprocessing': False,
        'calibration': False,
        'behavior_metrics': False,
        'bout_analysis': False,
        'bout_phase_analysis': False,
        'tracking': False,
        'multi_scale': False
    }
    
    # Check for detection data
    if 'bboxes' in root or 'detect_runs' in root:
        components['detection'] = True
    
    # Check for preprocessing
    if 'filtered_runs' in root or 'preprocessing' in root:
        components['preprocessing'] = True
    
    # Check for calibration
    if 'calibration' in root:
        components['calibration'] = True
    
    # Check for behavior metrics
    if 'behavior_metrics' in root:
        components['behavior_metrics'] = True
    
    # Check for bout analyses
    if 'bout_analysis' in root:
        components['bout_analysis'] = True
    
    if 'bout_phase_analysis' in root:
        components['bout_phase_analysis'] = True
    
    # Check for tracking data
    if 'tracking_runs' in root:
        components['tracking'] = True
        # Check if multi-scale
        if 'latest' in root['tracking_runs'].attrs:
            latest_run = root['tracking_runs'].attrs['latest']
            if f'tracking_runs/{latest_run}/tracking_results' in root:
                tracking_results = root[f'tracking_runs/{latest_run}/tracking_results']
                if 'column_names' in tracking_results.attrs:
                    column_names = tracking_results.attrs['column_names']
                    if len(column_names) >= 20 and 'bbox_x_norm_ds' in column_names:
                        components['multi_scale'] = True
    
    return components

def analyze_calibration(root, console):
    """Analyze and display calibration information."""
    if 'calibration' not in root:
        return
    
    calib = root['calibration']
    calib_table = Table(title="📐 Calibration Data", box=box.ROUNDED)
    calib_table.add_column("Parameter", style="cyan")
    calib_table.add_column("Value", style="yellow")
    calib_table.add_column("Units", style="green")
    
    if 'pixel_to_mm' in calib.attrs:
        pixel_to_mm = calib.attrs['pixel_to_mm']
        calib_table.add_row("Pixel to mm", f"{pixel_to_mm:.6f}", "mm/pixel")
        calib_table.add_row("mm to pixel", f"{1/pixel_to_mm:.2f}", "pixels/mm")
    
    if 'fish_length_mm' in calib.attrs:
        calib_table.add_row("Fish length", f"{calib.attrs['fish_length_mm']:.1f}", "mm")
    
    if 'arena_diameter_mm' in calib.attrs:
        calib_table.add_row("Arena diameter", f"{calib.attrs['arena_diameter_mm']:.1f}", "mm")
    
    if 'measured_fps' in calib.attrs:
        calib_table.add_row("Measured FPS", f"{calib.attrs['measured_fps']:.2f}", "Hz")
    
    if 'created_at' in calib.attrs:
        calib_table.add_row("Calibrated", format_timestamp(calib.attrs['created_at']), "")
    
    console.print(calib_table)

def analyze_bout_phases(root, console):
    """Analyze bout phase analysis results."""
    if 'bout_phase_analysis' not in root:
        return
    
    analysis_group = root['bout_phase_analysis']
    
    # Get latest run
    if 'latest' not in analysis_group.attrs:
        return
    
    latest = analysis_group.attrs['latest']
    run_group = analysis_group[latest]
    
    # Display phase comparison
    if 'summary_statistics' in run_group.attrs:
        stats = run_group.attrs['summary_statistics']
        
        phase_table = Table(title="🏊 Training Phase Bout Analysis", box=box.ROUNDED)
        phase_table.add_column("Phase", style="cyan")
        phase_table.add_column("Bouts", style="yellow", justify="right")
        phase_table.add_column("Rate (bouts/min)", style="green", justify="right")
        phase_table.add_column("Active %", style="magenta", justify="right")
        phase_table.add_column("Change from Pre", style="red", justify="right")
        
        if 'phase_comparison' in stats:
            for phase_name, phase_data in stats['phase_comparison'].items():
                phase_label = phase_name.replace('_', ' ').title()
                n_bouts = phase_data.get('n_bouts', 0)
                bout_rate = phase_data.get('bout_rate_per_min', 0)
                percent_active = phase_data.get('percent_active', 0)
                
                # Get change from pre-training
                change_str = "-"
                if 'bout_rate_change_from_pre' in phase_data:
                    change = phase_data['bout_rate_change_from_pre']
                    change_str = f"{change:+.1f}%"
                
                phase_table.add_row(
                    phase_label,
                    str(n_bouts),
                    f"{bout_rate:.1f}",
                    f"{percent_active:.1f}%",
                    change_str
                )
        
        console.print(phase_table)

def analyze_behavior_metrics(root, console):
    """Analyze behavior metrics if present."""
    if 'behavior_metrics' not in root:
        return
    
    metrics = root['behavior_metrics']
    
    metrics_table = Table(title="📊 Behavior Metrics", box=box.ROUNDED)
    metrics_table.add_column("Metric", style="cyan")
    metrics_table.add_column("Value", style="yellow")
    metrics_table.add_column("Units", style="green")
    
    # Check for distance metrics
    if 'distance' in metrics:
        dist_group = metrics['distance']
        if 'total_distance' in dist_group.attrs:
            total_dist = dist_group.attrs['total_distance']
            metrics_table.add_row("Total distance", f"{total_dist:.1f}", "pixels")
            
            # If calibration exists, show mm too
            if 'calibration' in root and 'pixel_to_mm' in root['calibration'].attrs:
                pixel_to_mm = root['calibration'].attrs['pixel_to_mm']
                total_mm = total_dist * pixel_to_mm
                metrics_table.add_row("Total distance", f"{total_mm:.1f}", "mm")
    
    # Check for speed metrics
    if 'speed' in metrics:
        speed_group = metrics['speed']
        if 'mean_speed' in speed_group.attrs:
            mean_speed = speed_group.attrs['mean_speed']
            metrics_table.add_row("Mean speed", f"{mean_speed:.1f}", "px/s")
            
            if 'calibration' in root and 'pixel_to_mm' in root['calibration'].attrs:
                pixel_to_mm = root['calibration'].attrs['pixel_to_mm']
                mean_speed_mm = mean_speed * pixel_to_mm
                metrics_table.add_row("Mean speed", f"{mean_speed_mm:.2f}", "mm/s")
        
        if 'max_speed' in speed_group.attrs:
            max_speed = speed_group.attrs['max_speed']
            metrics_table.add_row("Max speed", f"{max_speed:.1f}", "px/s")
    
    console.print(metrics_table)

def analyze_preprocessing_pipeline(root, console):
    """Analyze the preprocessing pipeline stages."""
    stages = []
    
    # Original data
    if 'n_detections' in root:
        n_det = root['n_detections'][:]
        coverage = (n_det > 0).sum() / len(n_det) * 100
        stages.append(('Original', coverage, len(n_det)))
    
    # Filtered data
    if 'filtered_runs' in root and 'latest' in root['filtered_runs'].attrs:
        latest = root['filtered_runs'].attrs['latest']
        n_det = root['filtered_runs'][latest]['n_detections'][:]
        coverage = (n_det > 0).sum() / len(n_det) * 100
        stages.append(('Filtered', coverage, len(n_det)))
    
    # Interpolated data
    if 'preprocessing' in root:
        if 'interpolated_runs' in root['preprocessing']:
            runs = root['preprocessing']['interpolated_runs']
            run_names = sorted([name for name in runs.keys() if name.startswith('run_')])
            if run_names:
                n_det = runs[run_names[-1]]['n_detections'][:]
                coverage = (n_det > 0).sum() / len(n_det) * 100
                stages.append(('Interpolated', coverage, len(n_det)))
        elif 'latest' in root['preprocessing'].attrs:
            latest = root['preprocessing'].attrs['latest']
            n_det = root['preprocessing'][latest]['n_detections'][:]
            coverage = (n_det > 0).sum() / len(n_det) * 100
            stages.append(('Interpolated', coverage, len(n_det)))
    
    if stages:
        pipeline_table = Table(title="🔧 Preprocessing Pipeline", box=box.ROUNDED)
        pipeline_table.add_column("Stage", style="cyan")
        pipeline_table.add_column("Coverage", style="yellow", justify="right")
        pipeline_table.add_column("Frames", style="green", justify="right")
        pipeline_table.add_column("Change", style="magenta", justify="right")
        
        prev_coverage = None
        for stage_name, coverage, frames in stages:
            change_str = "-"
            if prev_coverage is not None:
                change = coverage - prev_coverage
                change_str = f"{change:+.1f}%"
            
            pipeline_table.add_row(
                stage_name,
                f"{coverage:.1f}%",
                str(frames),
                change_str
            )
            prev_coverage = coverage
        
        console.print(pipeline_table)

def build_enhanced_tree(group: zarr.hierarchy.Group, tree_branch: Tree, max_depth: int = 3, current_depth: int = 0):
    """Builds an enhanced tree view with better formatting and depth control."""
    if current_depth >= max_depth:
        tree_branch.add("[dim]... (more groups/arrays)[/dim]")
        return
    
    group_items = sorted(list(group.groups()))
    dataset_items = sorted(list(group.arrays()))
    
    # Add groups with icons
    for name, grp_obj in group_items:
        # Choose icon based on group name
        if 'calibration' in name:
            icon = "📐"
        elif 'bout' in name:
            icon = "🏊"
        elif 'behavior' in name or 'metrics' in name:
            icon = "📊"
        elif 'preprocessing' in name or 'filtered' in name:
            icon = "🔧"
        elif 'runs' in name:
            icon = "🔄"
        else:
            icon = "📁"
        
        # Check if it has a 'latest' attribute
        latest_info = ""
        if 'latest' in grp_obj.attrs:
            latest = grp_obj.attrs['latest'].split('/')[-1]
            latest_info = f" [dim]→ {latest}[/dim]"
        
        branch = tree_branch.add(f"{icon} [bold blue]{name}/[/bold blue]{latest_info}")
        build_enhanced_tree(grp_obj, branch, max_depth, current_depth + 1)
    
    # Add arrays with better formatting
    for name, arr_obj in dataset_items:
        # Format array info
        shape_str = "×".join(map(str, arr_obj.shape))
        size_str = format_bytes(arr_obj.nbytes)
        
        # Choose icon based on array name
        if 'bbox' in name:
            icon = "📦"
        elif 'speed' in name or 'distance' in name:
            icon = "📈"
        elif 'mask' in name:
            icon = "🎭"
        else:
            icon = "📊"
        
        tree_branch.add(f"{icon} [green]{name}[/green] [dim]({shape_str}, {arr_obj.dtype}, {size_str})[/dim]")

def print_summary_panel(console: Console, root, components):
    """Print a summary panel of the zarr contents."""
    summary_lines = []
    
    # Basic info
    if 'fps' in root.attrs:
        summary_lines.append(f"Frame rate: {root.attrs['fps']} fps")
    
    if 'frame_count' in root.attrs:
        duration = root.attrs['frame_count'] / root.attrs.get('fps', 60) / 60
        summary_lines.append(f"Duration: {duration:.1f} minutes ({root.attrs['frame_count']} frames)")
    
    # Component status with emojis
    summary_lines.append("\nComponents:")
    status = "✅" if components['detection'] else "❌"
    summary_lines.append(f"  {status} Detection data")
    
    status = "✅" if components['preprocessing'] else "❌"
    summary_lines.append(f"  {status} Preprocessing (filtering/interpolation)")
    
    status = "✅" if components['calibration'] else "❌"
    summary_lines.append(f"  {status} Calibration (real-world units)")
    
    status = "✅" if components['behavior_metrics'] else "❌"
    summary_lines.append(f"  {status} Behavior metrics")
    
    status = "✅" if components['bout_analysis'] else "❌"
    summary_lines.append(f"  {status} Bout analysis")
    
    status = "✅" if components['bout_phase_analysis'] else "❌"
    summary_lines.append(f"  {status} Training phase analysis")
    
    # Data quality
    if 'n_detections' in root:
        n_det = root['n_detections'][:]
        coverage = (n_det > 0).sum() / len(n_det) * 100
        summary_lines.append(f"\nOriginal coverage: {coverage:.1f}%")
    
    # File size
    total_size = 0
    for path, dirs, files in os.walk(root.store.path if hasattr(root.store, 'path') else str(root.store)):
        for f in files:
            fp = os.path.join(path, f)
            if os.path.exists(fp):
                total_size += os.path.getsize(fp)
    summary_lines.append(f"Total size: {format_bytes(total_size)}")
    
    panel = Panel(
        "\n".join(summary_lines),
        title="📊 Zarr Archive Summary",
        border_style="cyan",
        padding=(1, 2)
    )
    console.print(panel)

def inspect_zarr_archive(zarr_path: str, tree_depth: int = 3):
    """Main function to inspect a Zarr archive."""
    console = Console()
    
    # Header
    console.rule(f"[bold cyan]Zarr Archive Inspector[/bold cyan]", style="cyan")
    console.print(f"[dim]Path: {os.path.abspath(zarr_path)}[/dim]\n")
    
    try:
        root = zarr.open(zarr_path, mode='r')
    except Exception as e:
        console.print(f"[bold red]Error:[/bold red] Could not open Zarr archive: {e}")
        return
    
    # Detect components
    components = detect_pipeline_components(root)
    
    # Summary panel
    print_summary_panel(console, root, components)
    
    # Archive structure tree
    console.print("\n[bold]📁 Archive Structure[/bold]")
    tree = Tree(f"[bold cyan]{os.path.basename(zarr_path)}[/bold cyan]")
    build_enhanced_tree(root, tree, max_depth=tree_depth)
    console.print(tree)
    
    # Component-specific analyses
    if components['calibration']:
        console.print()
        analyze_calibration(root, console)
    
    if components['preprocessing']:
        console.print()
        analyze_preprocessing_pipeline(root, console)
    
    if components['behavior_metrics']:
        console.print()
        analyze_behavior_metrics(root, console)
    
    if components['bout_phase_analysis']:
        console.print()
        analyze_bout_phases(root, console)
    
    # Metadata details for specific groups
    console.print("\n[bold] Metadata Details[/bold]")
    
    # Show latest runs for each analysis type
    analysis_groups = [
        ('filtered_runs', 'Filtering'),
        ('preprocessing', 'Interpolation'),
        ('bout_analysis', 'Bout Analysis'),
        ('bout_phase_analysis', 'Phase Analysis')
    ]
    
    for group_name, display_name in analysis_groups:
        if group_name in root:
            group = root[group_name]
            if 'latest' in group.attrs:
                latest = group.attrs['latest']
                console.print(f"\n[cyan]{display_name}:[/cyan]")
                console.print(f"  Latest run: [yellow]{latest}[/yellow]")
                
                # Get run details
                try:
                    if 'runs/' in latest:
                        run_group = group[latest.replace('runs/', 'runs/')]
                    else:
                        run_group = group[latest]
                    
                    if 'created_at' in run_group.attrs:
                        console.print(f"  Created: [green]{format_timestamp(run_group.attrs['created_at'])}[/green]")
                    
                    if 'parameters' in run_group.attrs:
                        params = run_group.attrs['parameters']
                        console.print(f"  Parameters: [dim]{json.dumps(params, indent=4)}[/dim]")
                except:
                    pass
    
    # Footer with tips
    console.print("\n" + "─" * 80)
    console.print("[dim] Tips:[/dim]")
    console.print("[dim]  • Use --depth to control tree depth[/dim]")
    console.print("[dim]  • Groups with '→' have a 'latest' run[/dim]")
    console.print("[dim]  • ✅ = component present, ❌ = component missing[/dim]")

def main():
    parser = argparse.ArgumentParser(
        description="Enhanced inspector for fish tracking Zarr archives.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("zarr_path", type=str, 
                       help="Path to the Zarr archive directory to inspect.")
    parser.add_argument("--depth", type=int, default=3,
                       help="Maximum depth for tree display (default: 3)")
    
    args = parser.parse_args()
    inspect_zarr_archive(args.zarr_path, tree_depth=args.depth)

if __name__ == "__main__":
    main()